### ISSUE TITLE
ビルド時に警告が表示される

### ISSUE THREAD

**Issue by mikoim** [dit-rohm/dit-rohm.com#153]
```
/cache/bundle-install/ruby/2.2.0/gems/htmlcompressor-0.1.2/lib/htmlcompressor/compressor.rb:112: warning: duplicated key at line 132 ignored: :javascript_compressor
/cache/bundle-install/ruby/2.2.0/gems/htmlcompressor-0.1.2/lib/htmlcompressor/compressor.rb:113: warning: duplicated key at line 133 ignored: :css_compressor
```

**Comment by Tamrin007** [comment]
'htmlcompressor' の version 0.2.0 では修正されているようです。
[Warnings with Ruby 2.2.0 · Issue #23 · paolochiodi/htmlcompressor](http://bit.ly/1MkDEQE)

[middleman/middleman-minify-html](http://bit.ly/1MkDNDQ)
が利用するバージョンを上げてくれるのを待つしか無い？

**Comment by mikoim** [comment]
middleman-minify-html
https://github.com/middleman/middleman-minify-html/blob/master/middleman-minify-html.gemspec

```ruby
s.add_runtime_dependency("htmlcompressor", ["~> 0.2.0"])
```

**Comment by Tamrin007** [comment]
むむっ？
Ruby神頼んだ
