### ISSUE TITLE
けいちゃんのプロフィールからウェブサイトに飛ぶとHTTPS接続になる

### ISSUE THREAD

**Issue by Tamrin007** [dit-rohm/dit-rohm.com#169]
正しくアクセス出来ない。

https://nakanishy.com/
http://nakanishy.com/

**Comment by Tamrin007** [comment]
うっちーさんのはてブも

**Comment by Tamrin007** [comment]
minify の 'Remove HTTP protocol' を見直す

**Comment by nakanishy** [comment]
3.4.1に上げる

**Comment by mikoim** [comment]
https://github.com/dit-rohm/dit-rohm.com/pull/172
