### ISSUE TITLE
トップページにソーシャルボタンを追加

### ISSUE THREAD

**Issue by nakanishy** [dit-rohm/dit-rohm.com#17]
・デプロイ後、はてブボタンが動くか確認

**Comment by Tamrin007** [comment]
パーシャルは容易してあります

**Comment by chikam** [comment]
どこに追加しよう...

* headerの中 
![dit_doshisha_institute_of_technology](https://cloud.githubusercontent.com/assets/8417896/8357279/1625acbc-1b95-11e5-8314-0c651fa6e3dd.png)

* footerの上
![dit_doshisha_institute_of_technology_](https://cloud.githubusercontent.com/assets/8417896/8357247/e2600f8a-1b94-11e5-9811-f7f6758d1fbb.png)
