### ISSUE TITLE
DITのマップが…消えた…？

### ISSUE THREAD

**Issue by Tamrin007** [dit-rohm/dit-rohm.com#173]
![capturfiles-201506170_230680](https://cloud.githubusercontent.com/assets/10954404/8256022/0e0ed4a0-16df-11e5-8034-aeabec14beef.png)

Error Msg: `Mixed Content: The page at 'https://dit-rohm.com/' was loaded over HTTPS, but requested an insecure script 'http://maps.google.com/maps/api/js?sensor=false'. This request has been blocked; the content must be served over HTTPS.`

**Comment by mikoim** [comment]
https://github.com/dit-rohm/dit-rohm.com/pull/174
ぬかりない（´・ω・） ｽ
