### ISSUE TITLE
s/開催します/開催しました/g

### ISSUE THREAD

**Issue by tomoyat1** [dit-rohm/dit-rohm.com#199]
DHacksに関する記述を過去形にする必要はありますか？

**Comment by nakanishy** [comment]
dhacksの宣伝用の青いバーはとりえあず消します
dhacksのことはaboutあたりにかいたらいいかなと

**Comment by tomoyat1** [comment]
なるほど。部分テンプレートは残しておいて最終的なページから取り除くだけですか。
やろうかと思ったのですがそれでいいのかわからなかったのでやめました。
